language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
#    - nightly

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/phpunit

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Static Analysis (informative)
            php: 7.4
            script:
                - composer run-script phpstan


    allow_failures:
        -   stage: Static Analysis (informative)


dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
